'use client'

import { useEffect, useMemo, useState } from 'react'
import { AlertCircle, Check, ChevronDown, Clapperboard, Download, FileAudio, Film, Gauge, Headphones, Loader2, Play, Settings2, Sparkles, WandSparkles } from 'lucide-react'
import { createVideo, generateScript, getMediaUrl, getTask, type TaskStatus } from '@/lib/api'

type Status = 'idle' | 'writing' | 'queued' | 'rendering' | 'complete' | 'error'
const voices = ['Default voice', 'en-US-AriaNeural-Female', 'en-US-GuyNeural-Male', 'zh-CN-XiaoxiaoNeural-Female']
const sources = ['Pexels', 'Pixabay', 'Local library', 'Mixkit']
const fieldClass = 'w-full rounded-xl border border-border bg-input px-3.5 py-3 text-sm text-foreground outline-none transition placeholder:text-muted-foreground focus:border-primary focus:ring-2 focus:ring-primary/20'

export function VideoStudio() {
  const [topic, setTopic] = useState('The quiet power of starting before you feel ready')
  const [script, setScript] = useState('Every meaningful project starts the same way: with a small decision to begin. You do not need perfect conditions, a flawless plan, or permission from anyone else. You just need one honest first step.\n\nMomentum is built in motion. Start with what you know, learn what you need, and let the work teach you the way forward.')
  const [aspect, setAspect] = useState('9:16')
  const [duration, setDuration] = useState(45)
  const [voice, setVoice] = useState(voices[0])
  const [source, setSource] = useState(sources[0])
  const [subtitles, setSubtitles] = useState(true)
  const [bgm, setBgm] = useState(true)
  const [status, setStatus] = useState<Status>('idle')
  const [progress, setProgress] = useState(0)
  const [task, setTask] = useState<TaskStatus | null>(null)
  const [error, setError] = useState('')
  const [showSettings, setShowSettings] = useState(false)

  useEffect(() => {
    if (!task?.task_id || !['queued', 'rendering'].includes(status)) return
    const timer = window.setInterval(async () => {
      try { const response = await getTask(task.task_id); setTask(response.data); setProgress(response.data.progress || 0); if (response.data.state === 2 || response.data.videos?.length || response.data.combined_videos?.length) { setStatus('complete'); setProgress(100); window.clearInterval(timer) } else if (response.data.error) { setStatus('error'); setError(response.data.error); window.clearInterval(timer) } }
      catch (cause) { setStatus('error'); setError(cause instanceof Error ? cause.message : 'Unable to read task status.'); window.clearInterval(timer) }
    }, 3000)
    return () => window.clearInterval(timer)
  }, [task?.task_id, status])

  const videoUrl = useMemo(() => { const file = task?.combined_videos?.[0] || task?.videos?.[0]; return file ? getMediaUrl(file) : '' }, [task])
  const generate = async () => {
    if (!topic.trim() || !script.trim()) { setError('Add a topic and a script before generating.'); setStatus('error'); return }
    setError(''); setStatus('queued'); setProgress(8)
    try { const response = await createVideo({ video_subject: topic, video_script: script, video_aspect: aspect, video_clip_duration: duration, voice_name: voice === voices[0] ? '' : voice, video_source: source.toLowerCase(), subtitle_enabled: subtitles, bgm_type: bgm ? 'random' : 'none', bgm_volume: 0.2 }); setTask({ task_id: response.data.task_id, state: 0, progress: 8 }) }
    catch (cause) { setStatus('error'); setError(cause instanceof Error ? cause.message : 'Could not queue the video.') }
  }
  const writeScript = async () => { if (!topic.trim()) return; setError(''); setStatus('writing'); try { const response = await generateScript(topic); setScript(response.data.video_script); setStatus('idle') } catch (cause) { setStatus('error'); setError(cause instanceof Error ? cause.message : 'Script generation is unavailable.') } }
  const label = status === 'idle' ? 'Ready to create' : status === 'writing' ? 'Writing your script' : status === 'queued' ? 'Queued for rendering' : status === 'rendering' ? 'Rendering video' : status === 'complete' ? 'Video ready' : 'Something needs attention'

  return <main className="min-h-screen px-4 py-5 md:px-8 lg:px-10">
    <header className="mx-auto flex max-w-[1480px] items-center justify-between border-b border-border/70 pb-5">
      <div className="flex items-center gap-3"><div className="flex size-9 items-center justify-center rounded-xl bg-primary text-primary-foreground shadow-lg shadow-primary/10"><Clapperboard className="size-5" /></div><div><p className="text-sm font-semibold tracking-wide">MONEYPRINTER<span className="text-primary">TURBO</span></p><p className="font-mono text-[10px] uppercase tracking-[.22em] text-muted-foreground">Creator studio</p></div></div>
      <div className="flex items-center gap-3"><span className="hidden rounded-full border border-border bg-card px-3 py-1.5 text-xs text-muted-foreground sm:inline-flex"><span className="mr-2 size-1.5 self-center rounded-full bg-emerald-400" />Backend connected</span><button onClick={() => setShowSettings(!showSettings)} className="rounded-lg border border-border bg-card p-2.5 text-muted-foreground transition hover:text-foreground" aria-label="Open settings"><Settings2 className="size-4" /></button><div className="flex size-9 items-center justify-center rounded-full bg-accent/20 text-xs font-semibold text-accent">MP</div></div>
    </header>
    <div className="mx-auto grid max-w-[1480px] gap-6 py-7 lg:grid-cols-[minmax(0,1.3fr)_minmax(360px,.7fr)]">
      <section className="flex flex-col gap-6">
        <div><p className="mb-2 font-mono text-xs uppercase tracking-[.2em] text-primary">New project</p><h1 className="text-balance text-3xl font-semibold tracking-tight md:text-4xl">Turn an idea into a <span className="text-primary">story.</span></h1><p className="mt-2 max-w-xl text-sm leading-6 text-muted-foreground">Shape your concept, tune the details, and let the studio handle the production.</p></div>
        <div className="glass rounded-2xl border border-border p-5 shadow-2xl shadow-black/10 md:p-6">
          <div className="mb-6 flex items-center justify-between"><div className="flex items-center gap-2"><WandSparkles className="size-4 text-primary" /><h2 className="font-medium">Story & script</h2></div><button onClick={writeScript} disabled={status === 'writing'} className="inline-flex items-center gap-2 rounded-lg border border-primary/30 bg-primary/10 px-3 py-2 text-xs font-medium text-primary transition hover:bg-primary/20 disabled:opacity-60">{status === 'writing' ? <Loader2 className="size-3.5 animate-spin" /> : <Sparkles className="size-3.5" />} Generate with AI</button></div>
          <label className="mb-2 block text-xs font-medium text-muted-foreground" htmlFor="topic">What is your video about?</label><input id="topic" className={fieldClass} value={topic} onChange={e => setTopic(e.target.value)} placeholder="Describe your idea..." />
          <div className="mt-5"><div className="mb-2 flex items-center justify-between"><label className="text-xs font-medium text-muted-foreground" htmlFor="script">Script</label><span className="font-mono text-[10px] text-muted-foreground">{script.length} characters</span></div><textarea id="script" className={`${fieldClass} min-h-44 resize-y leading-6`} value={script} onChange={e => setScript(e.target.value)} /></div>
        </div>
        <div className="glass rounded-2xl border border-border p-5 md:p-6"><div className="mb-6 flex items-center gap-2"><Gauge className="size-4 text-primary" /><h2 className="font-medium">Production settings</h2></div><div className="grid gap-5 sm:grid-cols-2">
          <div><label className="mb-2 block text-xs font-medium text-muted-foreground" htmlFor="aspect">Aspect ratio</label><select id="aspect" className={fieldClass} value={aspect} onChange={e => setAspect(e.target.value)}><option value="9:16">Portrait · 9:16</option><option value="16:9">Landscape · 16:9</option><option value="1:1">Square · 1:1</option></select></div>
          <div><label className="mb-2 block text-xs font-medium text-muted-foreground" htmlFor="duration">Clip duration · {duration}s</label><input id="duration" type="range" min="15" max="90" step="15" className="mt-3 w-full accent-primary" value={duration} onChange={e => setDuration(Number(e.target.value))} /><div className="mt-1 flex justify-between font-mono text-[10px] text-muted-foreground"><span>15s</span><span>90s</span></div></div>
          <div><label className="mb-2 block text-xs font-medium text-muted-foreground" htmlFor="voice">Voice / TTS</label><select id="voice" className={fieldClass} value={voice} onChange={e => setVoice(e.target.value)}>{voices.map(item => <option key={item}>{item}</option>)}</select></div>
          <div><label className="mb-2 block text-xs font-medium text-muted-foreground" htmlFor="source">Visual source</label><select id="source" className={fieldClass} value={source} onChange={e => setSource(e.target.value)}>{sources.map(item => <option key={item}>{item}</option>)}</select></div>
        </div><div className="mt-6 grid gap-3 border-t border-border pt-5 sm:grid-cols-2"><button onClick={() => setSubtitles(!subtitles)} className={`flex items-center justify-between rounded-xl border p-3 text-left transition ${subtitles ? 'border-primary/40 bg-primary/10' : 'border-border bg-input'}`}><span className="flex items-center gap-3"><span className={`flex size-7 items-center justify-center rounded-lg ${subtitles ? 'bg-primary text-primary-foreground' : 'bg-muted text-muted-foreground'}`}>{subtitles && <Check className="size-4" />}</span><span><span className="block text-sm">Subtitles</span><span className="block text-xs text-muted-foreground">Burn captions into video</span></span></span><ChevronDown className="size-4 text-muted-foreground" /></button><button onClick={() => setBgm(!bgm)} className={`flex items-center justify-between rounded-xl border p-3 text-left transition ${bgm ? 'border-primary/40 bg-primary/10' : 'border-border bg-input'}`}><span className="flex items-center gap-3"><span className={`flex size-7 items-center justify-center rounded-lg ${bgm ? 'bg-primary text-primary-foreground' : 'bg-muted text-muted-foreground'}`}>{bgm ? <Check className="size-4" /> : <Headphones className="size-4" />}</span><span><span className="block text-sm">Background music</span><span className="block text-xs text-muted-foreground">Add a subtle audio bed</span></span></span><ChevronDown className="size-4 text-muted-foreground" /></button></div></div>
        <div className="flex items-center gap-3"><button onClick={generate} disabled={status === 'queued' || status === 'rendering' || status === 'writing'} className="flex flex-1 items-center justify-center gap-2 rounded-xl bg-primary px-5 py-3.5 text-sm font-semibold text-primary-foreground shadow-lg shadow-primary/10 transition hover:brightness-110 disabled:cursor-not-allowed disabled:opacity-60">{status === 'queued' || status === 'rendering' ? <Loader2 className="size-4 animate-spin" /> : <Film className="size-4" />} Generate video</button><button onClick={() => setShowSettings(!showSettings)} className="rounded-xl border border-border bg-card p-3.5 text-muted-foreground hover:text-foreground" aria-label="Provider configuration"><Settings2 className="size-4" /></button></div>
        {showSettings && <div className="rounded-xl border border-accent/30 bg-accent/10 p-4 text-xs leading-5 text-accent">Provider configuration is managed by the Python backend. Keep API keys in its server environment; this browser never receives or stores secrets.</div>}
        {error && <div role="alert" className="flex items-start gap-2 rounded-xl border border-red-400/20 bg-red-400/10 p-3 text-sm text-red-200"><AlertCircle className="mt-0.5 size-4 shrink-0" />{error}</div>}
      </section>
      <aside className="flex flex-col gap-5"><div className="glass overflow-hidden rounded-2xl border border-border"><div className="flex items-center justify-between border-b border-border px-5 py-4"><div><p className="text-sm font-medium">Preview</p><p className="mt-0.5 text-xs text-muted-foreground">{label}</p></div><span className={`rounded-full px-2.5 py-1 font-mono text-[10px] uppercase tracking-wider ${status === 'complete' ? 'bg-emerald-400/10 text-emerald-300' : status === 'error' ? 'bg-red-400/10 text-red-300' : 'bg-muted text-muted-foreground'}`}>{status}</span></div><div className="flex min-h-[420px] items-center justify-center bg-black/20 p-5 md:min-h-[500px]">{videoUrl ? <video src={videoUrl} controls className="max-h-[500px] w-full rounded-xl" /> : <div className="flex max-w-xs flex-col items-center text-center"><div className="mb-5 flex size-16 items-center justify-center rounded-2xl border border-border bg-muted/60 text-muted-foreground"><Play className="ml-1 size-6" /></div><p className="text-sm font-medium">Your video will appear here</p><p className="mt-2 text-xs leading-5 text-muted-foreground">Configure your story and hit generate to see the first cut.</p></div>}</div>{(status === 'queued' || status === 'rendering') && <div className="border-t border-border px-5 py-4"><div className="mb-2 flex justify-between text-xs"><span className="text-muted-foreground">Rendering your story</span><span className="font-mono text-primary">{progress}%</span></div><div className="h-1.5 overflow-hidden rounded-full bg-muted"><div className="h-full rounded-full bg-primary transition-all duration-700" style={{ width: `${Math.max(progress, 8)}%` }} /></div></div>}{videoUrl && <div className="flex gap-3 border-t border-border p-4"><a href={videoUrl} download className="flex flex-1 items-center justify-center gap-2 rounded-lg bg-primary px-4 py-2.5 text-xs font-semibold text-primary-foreground"><Download className="size-3.5" /> Download video</a><span className="flex items-center gap-1 rounded-lg border border-border px-3 text-xs text-muted-foreground"><FileAudio className="size-3.5" /> MP4</span></div>}</div><div className="rounded-2xl border border-border bg-card/50 p-5"><div className="mb-4 flex items-center gap-2"><Sparkles className="size-4 text-accent" /><h3 className="text-sm font-medium">Studio notes</h3></div><ul className="flex flex-col gap-3 text-xs leading-5 text-muted-foreground"><li className="flex gap-2"><span className="mt-2 size-1 shrink-0 rounded-full bg-primary" />Shorter scripts tend to create more dynamic pacing.</li><li className="flex gap-2"><span className="mt-2 size-1 shrink-0 rounded-full bg-primary" />Portrait format is optimized for Reels, Shorts, and TikTok.</li></ul></div></aside>
    </div><footer className="mx-auto flex max-w-[1480px] items-center justify-between border-t border-border/70 pt-5 text-[10px] uppercase tracking-[.18em] text-muted-foreground"><span>MoneyPrinterTurbo · v1.0</span><span className="hidden sm:inline">AI-assisted video production</span></footer>
  </main>
}
